import { StyleSheet } from 'react-native';

const textStyles = StyleSheet.create({
  page1_accountconfirmation_group5803_group5785_group5781_3_large_200: {
    fontSize: 20.88800048828125,
    fontWeight: '200',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#444444',
  },
  page1_accountconfirmation_home_xlarge_semibold: {
    fontSize: 33,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_accountsuccessfullycreated_home_small_semibold: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_accountsuccessfullycreated_home_xlarge_semibold: {
    fontSize: 27,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_accountsuccessfullycreated_home_xlarge_semibold: {
    fontSize: 27,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_bookingdetails_group5888_home_small_bold: {
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_bookingdetails_group5891_home_small_regular: {
    fontSize: 15,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_bookingdetails_group5892_group5883_home_small_semibold: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_bookings_group5537_home_small_medium: {
    fontSize: 8,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_chat_frame22_chats_chat_iwanttoknowaboutyourportfolion_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_chat_frame22_chats_chat_time_1108pm_small_semibold: {
    fontSize: 8,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_chat_frame22_chats_chat_time_1108pm_small_semibold: {
    fontSize: 8,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#111827',
  },
  page1_chat_frame22_chats_chat_time_1108pm_small_semibold: {
    fontSize: 8,
    fontWeight: '600',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_chat_frame26_frame24_writeamessage_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_chat_frame37_frame50_frame49_tab_chat_small_semibold: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_chat_frame37_frame50_frame49_tab_frame46_12_small_bold: {
    fontSize: 8,
    fontWeight: 'bold',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_chat_frame37_frame50_frame49_tab_frame46_3_small_bold: {
    fontSize: 8,
    fontWeight: 'bold',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_chat_frame37_frame50_frame49_tab_frame46_7_small_bold: {
    fontSize: 8,
    fontWeight: 'bold',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#141b34',
  },
  page1_chat_frame37_frame50_frame49_tab_localfriend_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#111827',
  },
  page1_chat_frame37_frame50_frame49_tab_localfriend_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#141b34',
  },
  page1_chat_frame37_frame50_frame49_tab_notification_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#111827',
  },
  page1_chat_frame56_messagehome_frame53_frame51_liatnihrambutkuitem_small_regular: {
    fontSize: 11,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#111827',
  },
  page1_chat_frame56_messagehome_frame53_frame52_1108pm_small_semibold: {
    fontSize: 8,
    fontWeight: '600',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#111827',
  },
  page1_chat_frame56_messagehome_frame53_frame52_frame46_12_small_bold: {
    fontSize: 8,
    fontWeight: 'bold',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_chat_frame56_messagehome_frame53_frame52_frame46_3_small_bold: {
    fontSize: 8,
    fontWeight: 'bold',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_chat_frame56_messagehome_frame53_group5853_frame51_nikos_medium_semibold: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#111827',
  },
  page1_chat_frame56_messagehome_frame53_group5853_frame51_sentanattachmentemoji_small_semibold: {
    fontSize: 11,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#111827',
  },
  page1_chat_group6008_group6007_group6004_group6002_section_card_text_normaldiet_small_medium: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 1,
    color: '#343835',
  },
  page1_cityguide_group5495_group5493_home_small_semibold: {
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_cityguide_group5818_group5484_home_small_semibold: {
    fontSize: 10,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_cityguide_home_small_bold: {
    fontSize: 6,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_cityguide_home_small_semibold: {
    fontSize: 6,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreendetailedpage_group5379_home_medium_regular: {
    fontSize: 18,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreendetailedpage_group5868_home_large_medium: {
    fontSize: 23,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreendetailedpage_group5874_group5873_home_small_regular: {
    fontSize: 13,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#444444',
  },
  page1_experiencescreendetailedpage_group5874_group5873_home_small_semibold: {
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreendetailedpage_group5886_group5885_home_medium_semibold: {
    fontSize: 17,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreendetailedpage_home_xlarge_semibold: {
    fontSize: 27,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreenhomepage_group5854_group5856_group5363_group5855_home_small_regular: {
    fontSize: 11,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_experiencescreenhomepage_group5854_group5856_home_medium_bold: {
    fontSize: 19,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreenhomepage_group5862_group5859_group5858_group5379_home_small_regular: {
    fontSize: 9,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreenhomepage_group5862_group5859_home_small_regular: {
    fontSize: 10,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_experiencescreenhomepage_group5862_group5859_home_small_semibold: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_homepage_group5370_home_small_medium: {
    fontSize: 8,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_homepage_group5375_group5363_home_medium_semibold: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_homepage_group5375_group5363_home_small_300: {
    fontSize: 10,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_homepage_group5849_group5834_group5833_group5832_group5831_group5830_group5829_home_small_bold: {
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#0d0d0d',
  },
  page1_homepage_home_xlarge_bold: {
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_hoteliers_group5762_home_xlarge_bold: {
    fontSize: 25,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_hoteliers_group5996_group5708_home_small_bold: {
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_hoteliers_group5996_home_small_regular: {
    fontSize: 13,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_hoteliers_home_medium_semibold: {
    fontSize: 19,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_linkbookingpagewithwhatsapp_bookyourlocalexpeirencedirectly_medium_semibold: {
    fontSize: 17,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_linkbookingpagewithwhatsapp_group5887_group5858_group5379_home_small_regular: {
    fontSize: 13,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_localbandit_home_medium_bold: {
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_localbandit_home_small_semibold: {
    fontSize: 13,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_localbandit_home_xlarge_800: {
    fontSize: 36,
    fontWeight: '800',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_localbanditdetailashost_group5599_group5593_group5364_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_localbanditdetailashost_group5603_group5403_home_medium_bold: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_localbanditdetailashost_group5915_group5914_group5631_group5403_home_small_bold: {
    fontSize: 8,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_localbanditdetailashost_group5915_group5914_home_medium_semibold: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_localbanditdetailashost_group5915_group5914_home_small_300: {
    fontSize: 7,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_localbanditdetailashost_group5915_group5914_home_small_regular: {
    fontSize: 10,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_localbanditdetailashost_group5967_group5977_home_small_medium: {
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_localbanditdetailashost_group5979_group5976_group5475_group5468_group5465_group5464_group5409_group5364_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#979797',
  },
  page1_localbanditdetailashost_group5979_group5976_group5475_group5468_home_medium_medium: {
    fontSize: 18,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_localexperiencedetailsashost_group5978_group5476_group5468_group5465_group5464_group5409_group5364_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#868686',
  },
  page1_localexperiencedetailsashost_group5980_group5977_home_small_regular: {
    fontSize: 13,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_localexperiencedetailsashost_group5984_group5983_home_large_semibold: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_localexperiencedetailsashost_group5984_home_small_regular: {
    fontSize: 7,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_localfriend_group5708_home_medium_bold: {
    fontSize: 19,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_localfriend_group5999_group5466_group5461_group5409_group5364_home_small_regular: {
    fontSize: 13,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_mapillustration_buttomsheet_125reviews_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Poppins',
    letterSpacing: 0,
    color: '#3f445d',
  },
  page1_mapillustration_buttomsheet_47_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Poppins',
    letterSpacing: -0.11999999731779099,
    color: '#3f445d',
  },
  page1_mapillustration_buttomsheet_gastropub_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Poppins',
    letterSpacing: -0.11999999731779099,
    color: '#3f445d',
  },
  page1_mapillustration_buttomsheet_latestrecomendationsnearyou_latestrecomendationsnearyou_medium_medium: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Poppins',
    letterSpacing: 1,
    color: '#3b3838',
  },
  page1_mapillustration_buttomsheet_latestrecomendationsnearyou_seeall_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Poppins',
    letterSpacing: 1,
    color: '#3b3838',
  },
  page1_mapillustration_buttomsheet_nightlifejazzinjazz_large_semibold: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#1a1a1a',
  },
  page1_mapillustration_buttomsheet_westheimerrdnikis11athens_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Poppins',
    letterSpacing: 0.6000000000000001,
    color: '#1a1a1a',
  },
  page1_mapillustration_card_enteryouraddress_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 1,
    color: '#3c3c3c',
  },
  page1_mapillustration_group5817_hotels_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 1,
    color: '#ffb800',
  },
  page1_mapillustration_group5817_restaurants_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 1,
    color: '#0ca4fa',
  },
  page1_mapillustration_group5817_shopping_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 1,
    color: '#670cfa',
  },
  page1_mapillustration_group5817_work_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 1,
    color: '#ff0000',
  },
  page1_notification_group5955_group5954_home_small_medium: {
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_notification_home_large_medium: {
    fontSize: 20,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_personalinformationoftraveller_group5429_home_medium_medium: {
    fontSize: 18,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_personalinformationoftraveller_group5429_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_personalinformationoftraveller_group5949_group5944_group5637_home_small_medium: {
    fontSize: 13,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_personalinformationoftraveller_group5962_group5942_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_personalinformationoftraveller_home_small_bold: {
    fontSize: 9,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_recoverypassword1_group5774_home_small_200: {
    fontSize: 14,
    fontWeight: '200',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_recoverypassword1_group5780_group5773_home_medium_200: {
    fontSize: 16,
    fontWeight: '200',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_recoverypassword4_home_xlarge_semibold: {
    fontSize: 32,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_scamalert_group5969_home_small_medium: {
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#141b34',
  },
  page1_scamalert_group5971_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#141b34',
  },
  page1_singin_group5776_home_small_200: {
    fontSize: 14,
    fontWeight: '200',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_singin_group5776_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#fa370c',
  },
  page1_singin_group5779_home_medium_semibold: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_singup_group5802_home_medium_semibold: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#fa370c',
  },
  page1_singup_group5816_group5815_group5794_home_small_300: {
    fontSize: 14,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_singup_group5827_group5800_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_singup_group5827_group5800_home_small_semibold: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_travelerwhento_group5363_group5736_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_travelerwhento_group5363_group5736_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_travelerwhento_group5650_group5363_home_medium_regular: {
    fontSize: 16,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_travelerwhento_group5651_home_medium_medium: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_travelerwhento_group5655_group5661_group5660_home_small_medium: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_travelerwhento_group5671_group5721_group5647_group5403_home_medium_bold: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_travelerwhento_group5821_bringingaserviceanimal_small_semibold: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_travelerwhento_group5821_group5649_home_medium_medium: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#5f5f5f',
  },
  page1_travelerwhento_group5821_group5666_group5665_home_large_medium: {
    fontSize: 20,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page1_travelerwhereto_group5850_group5834_group5833_group5832_group5831_group5830_group5829_home_small_regular: {
    fontSize: 10,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#0d0d0d',
  },
  page1_travelerwhereto_group5850_group5835_home_small_bold: {
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_travelerwhereto_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page1_welcomepage_group5355_0511_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_welcomepage_home_small_300: {
    fontSize: 15,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_welcomepage_home_small_bold: {
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page1_wishlist_home_xlarge_bold: {
    fontSize: 44,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page1_wishlistuserflow_group6016_home_medium_medium: {
    fontSize: 18,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page1_wishlistuserflow_home_small_bold: {
    fontSize: 13,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_allhotelshotels_group5678_group5676_home_small_semibold: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page2_allhotelshotels_group5678_group5676_home_small_semibold: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#0ab01a',
  },
  page2_allhotelshotels_group5678_group5677_group5363_home_medium_semibold: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_allhotelshotels_group5679_group5676_group5589_home_medium_regular: {
    fontSize: 18,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page2_allhotelshotels_group5679_group5676_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#0ab01a',
  },
  page2_annas_group5509_group5472_home_xlarge_semibold: {
    fontSize: 28,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_annas_group5509_home_medium_regular: {
    fontSize: 16,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_annas_group5518_group5481_group5475_group5468_group5465_group5464_group5409_group5364_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_annas_group5579_group5511_group5400_home_small_300: {
    fontSize: 7,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_annas_group5579_group5511_group5400_home_small_300: {
    fontSize: 6,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#868686',
  },
  page2_annas_group5579_group5511_group5400_home_small_medium: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_annas_group5579_group5511_group5401_group5483_group5482_group5481_group5480_group5376_home_small_bold: {
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_annas_group5579_group5511_group5401_group5483_group5482_group5481_group5480_group5376_home_small_regular: {
    fontSize: 8,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page2_annas_group5579_group5511_group5401_group5483_group5482_home_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_annas_group5579_group5511_group5401_group5483_group5482_home_xlarge_semibold: {
    fontSize: 24,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_apply_group5583_home_small_medium: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#0ab01a',
  },
  page2_becomealocalbandit_home_large_semibold: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_becomealocalbandit_home_small_300: {
    fontSize: 12,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_becomealocalbandit_home_small_medium: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_bookings_group5542_group5481_group5376_home_small_regular: {
    fontSize: 8,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_calendars2_group5562_home_small_semibold: {
    fontSize: 8,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_calendars2_group5743_group5742_home_xlarge_medium: {
    fontSize: 24,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_calenders_group5733_group5731_group5524_group5364_home_medium_medium: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_chat_frame10_frame29_nikosalexandrou_xlarge_semibold: {
    fontSize: 24,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#111827',
  },
  page2_chat_frame10_frame32_frame30_whatsappcall_small_semibold: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_chat_frame41_frame39_frame38_default_small_regular: {
    fontSize: 11,
    fontWeight: 'normal',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#111827',
  },
  page2_chat_frame41_frame39_frame38_notification_small_semibold: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#111827',
  },
  page2_chat_frame41_frame41_frame38_block_small_semibold: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#e63e19',
  },
  page2_chat_frame41_frame43_frame38_color_small_semibold: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#111827',
  },
  page2_chooseroom_group5705_group5699_group5403_home_medium_bold: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_chooseroom_group5705_group5704_group5699_home_large_bold: {
    fontSize: 22,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_chooseroom_group5705_group5704_group5700_home_small_medium: {
    fontSize: 9,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_chooseroom_group5705_home_small_200: {
    fontSize: 9,
    fontWeight: '200',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_confirmedinformation_group5461_home_large_semibold: {
    fontSize: 22,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_confirmedinformation_group5461_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ececec',
  },
  page2_editprofile_group5422_group5415_group5364_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_homepage_group5374_group5362_group5361_home_small_regular: {
    fontSize: 10,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_homepage_group5386_home_small_bold: {
    fontSize: 8,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#77ff47',
  },
  page2_homepage_group5481_group5480_group5383_group5379_home_small_semibold: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_hosting_group5559_group5547_group5524_group5411_group5364_home_small_semibold: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_hoteldetails_group5691_home_small_medium: {
    fontSize: 8,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_hoteldetails_group5698_group5697_home_xlarge_semibold: {
    fontSize: 28,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page2_hoteldetails_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#9f9f9f',
  },
  page2_insights_group5723_home_xlarge_bold: {
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_insights_group5765_group5724_home_small_300: {
    fontSize: 6,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page2_insights_group5765_group5724_home_small_300: {
    fontSize: 12,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_insights_group5766_home_medium_bold: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_insights_group5770_group5647_group5403_home_small_bold: {
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page2_insights_group5770_home_small_300: {
    fontSize: 12,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_insights_group5770_home_xlarge_bold: {
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_menu_group5529_group5485_home_medium_semibold: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_menu_group5530_home_small_regular: {
    fontSize: 10,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page2_paymentpayouts_group5515_group5509_group5472_home_xlarge_semibold: {
    fontSize: 28,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_paymentpayouts_group5515_group5509_home_small_medium: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_personalinformation_group5355_0511_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Open Sans',
    letterSpacing: 0,
    color: '#fafafa',
  },
  page2_personalinformation_home_medium_medium: {
    fontSize: 18,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#fafafa',
  },
  page2_personalinformation_home_xlarge_bold: {
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#fafafa',
  },
  page2_reservations_group5757_group5672_group5516_group5457_home_small_300: {
    fontSize: 9,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_reservations_group5757_group5672_group5516_group5457_home_small_300: {
    fontSize: 9,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_reservations_group5757_group5672_group5516_group5457_home_small_300: {
    fontSize: 9,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page2_reservations_group5758_home_small_medium: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_showprofile_group5447_home_small_medium: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_showprofile_group5456_group5441_group5430_group5427_group5409_group5364_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_stayout_group5717_home_small_bold: {
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_stayout_home_xlarge_bold: {
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#000000',
  },
  page2_submitapplication_group5577_group5516_group5457_home_small_300: {
    fontSize: 9,
    fontWeight: '300',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#fa370c',
  },
  page2_submitapplication_group5599_group5595_group5364_home_small_regular: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#fafafa',
  },
  page2_sumbit_group5625_group5364_home_xlarge_regular: {
    fontSize: 36,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ff0000',
  },
  page2_sumbit_home_small_regular: {
    fontSize: 9,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#fafafa',
  },
  page2_sumbit_home_small_regular: {
    fontSize: 9,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page2_travelerscreen_group5394_group5393_group5392_home_small_semibold: {
    fontSize: 10,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_travelerscreen_group5394_home_small_regular: {
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#8e8e8e',
  },
  page2_travelerscreen_home_small_semibold: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#0094e8',
  },
  page2_travelerwhen_group5763_home_medium_medium: {
    fontSize: 18,
    fontWeight: '500',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#777777',
  },
  page2_travelinabottle_group5719_group5703_home_large_bold: {
    fontSize: 22,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_travelinabottle_group5719_home_small_200: {
    fontSize: 9,
    fontWeight: '200',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#3c3c3c',
  },
  page2_travelinabottle_group5720_home_small_regular: {
    fontSize: 9,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_travelinabottle_group5720_home_small_regular: {
    fontSize: 10,
    fontWeight: 'normal',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
  page2_travelinabottle_group5761_group5760_home_xlarge_bold: {
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: 'Caros',
    letterSpacing: 0,
    color: '#ffffff',
  },
});

export default textStyles;
