/**
 * Phase 1 curated network signal library (premium, short, emotionally intriguing).
 * Seeded into `network_signal` via migration; kept in sync for offline fallback.
 */
export const SIGNAL_BANK_LINES = [
  'Trust the street with no sign.',
  'Some nights begin after midnight.',
  'Follow music, not maps.',
  'Cities reward curiosity.',
  'Arrive hungry for the wrong turn.',
  'The best room is the one you leave.',
  'Listen for laughter behind closed doors.',
  'Shadows know the shortcuts.',
  'Order what you cannot pronounce.',
  'Dawn belongs to the restless.',
  'Leave the guidebook at the door.',
  'Ask the barista where they go.',
  'Neon remembers everyone.',
  'Walk until the crowd thins.',
  'The stairs usually know.',
  'Silence is a kind of invitation.',
  'Borrow courage from strangers.',
  'Rain makes the city honest.',
  'Sit where locals stand.',
  'Forget the landmark; find the alley.',
  'Your feet already decided.',
  'The second cafe is often the truth.',
  'Windows lit at three a.m. are sermons.',
  'Cross the river on purpose.',
  'Hunger is a compass.',
  'The old sign is sometimes new.',
  'Whisper when the street is loud.',
  'Take the longer light.',
  'Benches hold confessions.',
  'Follow the dog.',
  'The corner shop knows your name tomorrow.',
  'Buy the ticket to nowhere.',
  'Smell bread before you see it.',
  'Elevators lie; stairs confess.',
  'If it feels forbidden, look closer.',
  'The city forgives tourists who stay curious.',
  'Wear comfortable shoes and doubt.',
  'The map ends where you begin.',
  'A line waits in the graffiti.',
  'The harbor always answers.',
  'Choose the narrow door.',
  'Tables for two are conspiracies.',
  'The bell rings for wanderers.',
  'Park where it feels unsafe; walk back brave.',
  'Ice in the glass, heat in the street.',
  'Rooflines tell the real story.',
  'Crosswalks are suggestions.',
  'The museum closes; the city opens.',
  'Borrow light from windows.',
  'If you are lost, you are close.',
  'The night shift runs the city.',
  'Stairs down often lead up.',
  'Wear your curiosity like a coat.',
  'The river remembers every footstep.',
  'Ask twice; the first answer is polite.',
  'The quiet street is a promise.',
  'Follow the steam from the kitchen.',
  'Coins in the fountain are wishes for strangers.',
  'The side door is the real entrance.',
  'Lanterns are invitations.',
  'The city hums in B minor.',
  'Trust the queue with locals.',
  'The balcony knows the weather.',
  'If music spills, follow it.',
  'The cracked pavement is honest.',
  'Sunset is a handoff.',
  'The vendor\'s nod is a visa.',
  'Walk away from the selfie.',
  'The clock tower is a suggestion.',
  'Fog makes strangers kin.',
  'The market opens before dawn.',
  'Choose the chair with a view of the door.',
  'The city rewards the early wrong turn.',
  'Bridges are promises.',
  'If it smells like citrus, stay.',
  'The spiral stair is a plot twist.',
  'Borrow time from tomorrow.',
  'The mural is a map.',
  'Raincoats are optimism.',
  'The tram knows your stop before you do.',
  'Sit until the espresso cools.',
  'The fountain is a meeting point for souls.',
  'Trust the hand-painted menu.',
  'The cobblestones remember.',
  'If the cat sits, you sit.',
  'The harbor wind is a compass.',
  'Choose the table in the corner.',
  'The city whispers in dialect.',
  'Neon is a lighthouse for night owls.',
  'The bakery opens secrets.',
  'Follow the smell of roasting.',
  'The park bench is a classroom.',
  'If you hesitate, turn left.',
  'The rooftop is a confession.',
  'The city rewards the soft gaze.',
  'Borrow courage from the river.',
  'The second glass is geography.',
  'The alley is a shortcut to yourself.',
  'Trust the stranger who points once.',
  'The city is a bottle; you are the message.',
  'Walk until the shoes agree.',
  'The night market is a parliament.',
  'If the door sticks, push gently.',
  'The city saves the best for the lost.',
  'Follow the echo, not the echo chamber.',
  'The tide sorts the brave.',
  'Sit where the light is tired.',
  'The city rewards the unscheduled hour.',
  'Choose curiosity over certainty.',
  'The stairwell smells like story.',
  'If the bell rings, answer.',
  'The map is a rumor; the street is fact.',
  'Borrow silence from the square.',
  'The city opens for the willing.',
  'Trust the detour with flowers.',
  'The last train is a poem.',
  'If you arrive empty-handed, listen harder.',
  'The city is older than your plan.',
  'Follow the thread of saxophone.',
  'The window box is a welcome mat.',
  'Choose the vendor who sings.',
  'The city rewards the slow yes.',
  'Walk until the horizon blushes.',
  'The fountain\'s chill is a dare.',
  'If the crowd parts, walk through.',
  'The city keeps score in footsteps.',
  'Borrow warmth from crowded tables.',
  'The night is a soft invitation.',
  'Trust the hand that offers water.',
  'The city is a network; you just arrived.',
] as const;

export const SIGNAL_BANK_COUNT = SIGNAL_BANK_LINES.length;
