import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from "pdf-lib";
import type { ProfessionalReportData } from "@/lib/reports/types";

const NAVY = rgb(0.06, 0.14, 0.26);
const GOLD = rgb(0.545, 0.42, 0.09);
const SLATE = rgb(0.2, 0.25, 0.33);
const MUTED = rgb(0.45, 0.51, 0.58);
const ROSE = rgb(0.74, 0.07, 0.24);
const EMERALD = rgb(0.06, 0.46, 0.43);
const AMBER = rgb(0.545, 0.42, 0.09);

type Fonts = { regular: PDFFont; bold: PDFFont };

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number) {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(next, size) <= maxWidth) {
      current = next;
    } else {
      if (current) lines.push(current);
      current = word;
    }
  }

  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

function drawWrapped(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  font: PDFFont,
  size: number,
  maxWidth: number,
  color = SLATE,
  lineHeight = size * 1.45,
) {
  let cursorY = y;
  for (const line of wrapText(text, font, size, maxWidth)) {
    page.drawText(line, { x, y: cursorY, size, font, color });
    cursorY -= lineHeight;
  }
  return cursorY;
}

function drawPageFooter(page: PDFPage, fonts: Fonts, pageNumber: number, totalPages: number) {
  page.drawText(`SafeKey Professional Report · Page ${pageNumber} of ${totalPages}`, {
    x: 50,
    y: 32,
    size: 8,
    font: fonts.regular,
    color: MUTED,
  });
  page.drawText("Confidential · For landlord use only", {
    x: 380,
    y: 32,
    size: 8,
    font: fonts.regular,
    color: MUTED,
  });
}

function drawSectionTitle(page: PDFPage, fonts: Fonts, title: string, y: number) {
  page.drawText(title, { x: 50, y, size: 18, font: fonts.bold, color: NAVY });
  page.drawLine({
    start: { x: 50, y: y - 8 },
    end: { x: 545, y: y - 8 },
    thickness: 1,
    color: rgb(0.9, 0.92, 0.94),
  });
  return y - 28;
}

function drawLabelValue(page: PDFPage, fonts: Fonts, label: string, value: string, x: number, y: number) {
  page.drawText(label, { x, y, size: 9, font: fonts.regular, color: MUTED });
  page.drawText(value, { x, y: y - 14, size: 11, font: fonts.bold, color: SLATE });
  return y - 36;
}

function riskColor(level: string) {
  if (level === "low") return EMERALD;
  if (level === "medium") return AMBER;
  return ROSE;
}

function drawCoverPage(page: PDFPage, fonts: Fonts, data: ProfessionalReportData) {
  page.drawRectangle({ x: 0, y: 720, width: 595, height: 122, color: NAVY });
  page.drawText("SafeKey", { x: 50, y: 760, size: 28, font: fonts.bold, color: rgb(1, 1, 1) });
  page.drawText("Professional Tenant Report", {
    x: 50,
    y: 732,
    size: 12,
    font: fonts.regular,
    color: rgb(0.85, 0.88, 0.92),
  });

  let y = 660;
  page.drawText("Tenant Screening Report", { x: 50, y, size: 22, font: fonts.bold, color: NAVY });
  y -= 36;
  y = drawLabelValue(page, fonts, "Report date", data.reportDate, 50, y);
  y = drawLabelValue(page, fonts, "Tenant name", data.tenantName, 50, y);
  if (data.propertyName) {
    y = drawLabelValue(page, fonts, "Property", data.propertyName, 50, y);
  }
  y = drawLabelValue(page, fonts, "Report ID", data.reportId, 50, y);
  y = drawLabelValue(page, fonts, "Verification status", data.verificationStatus, 50, y);

  page.drawRectangle({
    x: 50,
    y: y - 60,
    width: 495,
    height: 48,
    color: rgb(0.97, 0.98, 0.99),
    borderColor: rgb(0.88, 0.91, 0.94),
    borderWidth: 1,
  });
  page.drawText("This report was generated by SafeKey AI analysis for Greek rental screening.", {
    x: 62,
    y: y - 38,
    size: 10,
    font: fonts.regular,
    color: MUTED,
  });
}

function drawTenantSummary(page: PDFPage, fonts: Fonts, data: ProfessionalReportData) {
  let y = drawSectionTitle(page, fonts, "Tenant Summary", 780);
  const left = 50;
  const right = 310;
  const ratio =
    data.tenant.incomeToRentRatio != null
      ? `${(data.tenant.incomeToRentRatio * 100).toFixed(1)}%`
      : "Not calculated";

  y = drawLabelValue(page, fonts, "Full name", data.tenant.fullName, left, y);
  drawLabelValue(page, fonts, "Email", data.tenant.email ?? "—", right, y + 36);
  y -= 36;
  y = drawLabelValue(page, fonts, "Phone", data.tenant.phone ?? "—", left, y);
  drawLabelValue(page, fonts, "Nationality", data.tenant.nationality ?? "Not provided", right, y + 36);
  y -= 36;
  y = drawLabelValue(page, fonts, "Occupation", data.tenant.occupation ?? "Not provided", left, y);
  drawLabelValue(
    page,
    fonts,
    "Monthly income",
    data.tenant.monthlyIncome != null ? `EUR ${data.tenant.monthlyIncome.toLocaleString()}` : "—",
    right,
    y + 36,
  );
  y -= 36;
  y = drawLabelValue(
    page,
    fonts,
    "Requested rent",
    data.tenant.requestedRent != null ? `EUR ${data.tenant.requestedRent.toLocaleString()}` : "—",
    left,
    y,
  );
  drawLabelValue(page, fonts, "Income-to-rent ratio", ratio, right, y + 36);
}

function drawRiskAssessment(page: PDFPage, fonts: Fonts, data: ProfessionalReportData) {
  let y = drawSectionTitle(page, fonts, "SafeKey Risk Assessment", 780);
  const { assessment } = data;

  page.drawCircle({
    x: 120,
    y: y - 70,
    size: 56,
    borderColor: riskColor(assessment.riskLevel),
    borderWidth: 4,
  });
  const scoreX = assessment.score >= 100 ? 98 : assessment.score >= 10 ? 104 : 110;
  page.drawText(String(assessment.score), {
    x: scoreX,
    y: y - 78,
    size: 28,
    font: fonts.bold,
    color: NAVY,
  });
  page.drawText("/100", { x: 138, y: y - 92, size: 10, font: fonts.regular, color: MUTED });
  page.drawText("SafeKey Score", { x: 78, y: y - 118, size: 10, font: fonts.bold, color: SLATE });

  y = drawLabelValue(page, fonts, "Risk Level", assessment.riskLevelLabel, 240, y);
  page.drawRectangle({
    x: 240,
    y: y + 8,
    width: 72,
    height: 20,
    color: riskColor(assessment.riskLevel),
  });
  page.drawText(assessment.riskLevelLabel, {
    x: 252,
    y: y + 12,
    size: 10,
    font: fonts.bold,
    color: rgb(1, 1, 1),
  });

  y -= 20;
  y = drawLabelValue(page, fonts, "Recommendation", assessment.recommendationLabel, 240, y);
  drawWrapped(page, data.explanation.summary, 50, y - 24, fonts.regular, 10, 495, MUTED);
}

function drawDocumentsReview(page: PDFPage, fonts: Fonts, data: ProfessionalReportData) {
  let y = drawSectionTitle(page, fonts, "Documents Review", 780);

  page.drawText("Uploaded Documents", { x: 50, y, size: 12, font: fonts.bold, color: NAVY });
  y -= 22;

  if (data.uploadedDocuments.length === 0) {
    drawWrapped(page, "No documents uploaded.", 50, y, fonts.regular, 10, 495, MUTED);
  } else {
    for (const doc of data.uploadedDocuments) {
      page.drawText("+", { x: 50, y, size: 11, font: fonts.bold, color: EMERALD });
      page.drawText(doc, { x: 68, y, size: 11, font: fonts.regular, color: SLATE });
      y -= 18;
    }
  }

  y -= 16;
  page.drawText("Missing Documents", { x: 50, y, size: 12, font: fonts.bold, color: ROSE });
  y -= 22;

  if (data.missingDocuments.length === 0) {
    page.drawRectangle({
      x: 50,
      y: y - 28,
      width: 495,
      height: 32,
      color: rgb(0.94, 0.99, 0.97),
      borderColor: rgb(0.75, 0.92, 0.86),
      borderWidth: 1,
    });
    page.drawText("All requested documents were submitted.", {
      x: 62,
      y: y - 18,
      size: 10,
      font: fonts.regular,
      color: EMERALD,
    });
  } else {
    for (const doc of data.missingDocuments) {
      page.drawRectangle({
        x: 50,
        y: y - 20,
        width: 495,
        height: 24,
        color: rgb(1, 0.97, 0.97),
        borderColor: rgb(0.98, 0.85, 0.87),
        borderWidth: 1,
      });
      page.drawText("!", { x: 58, y: y - 16, size: 11, font: fonts.bold, color: ROSE });
      page.drawText(doc, { x: 72, y: y - 16, size: 11, font: fonts.bold, color: ROSE });
      y -= 28;
    }
  }

  y -= 16;
  page.drawText("Financial Reliability", { x: 50, y, size: 12, font: fonts.bold, color: NAVY });
  y -= 22;
  y = drawLabelValue(
    page,
    fonts,
    "Credit Report",
    data.financialReliability.creditReport === "uploaded" ? "Uploaded" : "Not uploaded",
    240,
    y,
  );
  drawLabelValue(
    page,
    fonts,
    "Credit Score",
    data.financialReliability.creditScore === "available" ? "Available" : "Not available",
    240,
    y,
  );
  drawWrapped(
    page,
    "SafeKey only accepts the official PDF obtained directly by the tenant from Tiresias. Bank passwords and online banking credentials are never requested.",
    50,
    y - 36,
    fonts.regular,
    9,
    495,
    MUTED,
  );
}

function drawRedFlags(page: PDFPage, fonts: Fonts, data: ProfessionalReportData) {
  let y = drawSectionTitle(page, fonts, "Red Flags", 780);

  if (data.redFlags.length === 0) {
    drawWrapped(
      page,
      "No material red flags were identified in this screening file.",
      50,
      y,
      fonts.regular,
      11,
      495,
      EMERALD,
    );
    return;
  }

  for (const flag of data.redFlags) {
    page.drawRectangle({
      x: 50,
      y: y - 36,
      width: 495,
      height: 40,
      color: rgb(1, 0.97, 0.97),
      borderColor: rgb(0.98, 0.85, 0.87),
      borderWidth: 1,
    });
    y = drawWrapped(page, flag, 62, y - 14, fonts.regular, 10, 470, ROSE) - 8;
    y -= 8;
  }
}

function drawAiExplanation(page: PDFPage, fonts: Fonts, data: ProfessionalReportData) {
  let y = drawSectionTitle(page, fonts, "AI Explanation", 780);

  page.drawText("Why this score was assigned", { x: 50, y, size: 11, font: fonts.bold, color: NAVY });
  y -= 18;
  y = drawWrapped(page, data.explanation.summary, 50, y, fonts.regular, 10, 495, SLATE) - 12;

  page.drawText("Strengths", { x: 50, y, size: 11, font: fonts.bold, color: EMERALD });
  y -= 16;
  for (const item of data.explanation.strengths.slice(0, 4)) {
    y = drawWrapped(page, `- ${item}`, 58, y, fonts.regular, 10, 487, SLATE) - 4;
  }
  y -= 8;

  page.drawText("Concerns", { x: 50, y, size: 11, font: fonts.bold, color: ROSE });
  y -= 16;
  const concerns =
    data.explanation.concerns.length > 0 ? data.explanation.concerns : ["No additional concerns recorded."];
  for (const item of concerns.slice(0, 4)) {
    y = drawWrapped(page, `- ${item}`, 58, y, fonts.regular, 10, 487, SLATE) - 4;
  }
  y -= 8;

  page.drawText("Suggested landlord actions", { x: 50, y, size: 11, font: fonts.bold, color: GOLD });
  y -= 16;
  for (const item of data.explanation.suggestedActions.slice(0, 4)) {
    y = drawWrapped(page, `- ${item}`, 58, y, fonts.regular, 10, 487, SLATE) - 4;
  }

  page.drawText(`Report schema ${data.partnerSchemaVersion}`, {
    x: 50,
    y: 48,
    size: 8,
    font: fonts.regular,
    color: MUTED,
  });
}

export async function generateProfessionalReportPdf(data: ProfessionalReportData): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`SafeKey Report · ${data.tenantName}`);
  pdf.setAuthor("SafeKey");
  pdf.setSubject("Tenant screening report");
  pdf.setCreator("SafeKey Professional Report System");

  const fonts: Fonts = {
    regular: await pdf.embedFont(StandardFonts.Helvetica),
    bold: await pdf.embedFont(StandardFonts.HelveticaBold),
  };

  const totalPages = 6;
  const pageDrawers = [
    (page: PDFPage) => drawCoverPage(page, fonts, data),
    (page: PDFPage) => drawTenantSummary(page, fonts, data),
    (page: PDFPage) => drawRiskAssessment(page, fonts, data),
    (page: PDFPage) => drawDocumentsReview(page, fonts, data),
    (page: PDFPage) => drawRedFlags(page, fonts, data),
    (page: PDFPage) => drawAiExplanation(page, fonts, data),
  ];

  pageDrawers.forEach((draw, index) => {
    const page = pdf.addPage([595, 842]);
    draw(page);
    drawPageFooter(page, fonts, index + 1, totalPages);
  });

  return pdf.save();
}
